// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:007d2a07-8db0-4315-afad-146652f2bf0a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_GB1AUJK36",
    "aws_user_pools_web_client_id": "3aguvpc7aoquutpd6n08alpnvg",
    "oauth": {},
    "aws_content_delivery_bucket": "laneone-20191216191850-hostingbucket-nordstrom",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://laneone-20191216191850-hostingbucket-nordstrom.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
